# Generated by Django 6.0.3 on 2026-04-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Предмет корзины', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Элемент заказа', 'verbose_name_plural': 'Элементы заказа'},
        ),
        migrations.AddField(
            model_name='order',
            name='items_m2m',
            field=models.ManyToManyField(related_name='orders_m2m', through='core.OrderItem', through_fields=('order', 'antique_item'), to='core.antiqueitem'),
        ),
    ]
