# Generated by Django 6.0.3 on 2026-04-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cartitem_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiqueitem',
            name='additional_categories',
            field=models.ManyToManyField(blank=True, related_name='additional_items', to='core.category', verbose_name='Дополнительные категории'),
        ),
    ]
