# Generated by Django 6.0.3 on 2026-04-26 13:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_antiqueitem_additional_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название аукциона')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящий'), ('active', 'Активный'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='upcoming', max_length=20, verbose_name='Статус')),
                ('image', models.ImageField(blank=True, null=True, upload_to='auctions/', verbose_name='Изображение аукциона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Аукцион',
                'verbose_name_plural': 'Аукционы',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='antiqueitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='antiqueitem',
            name='certificate_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Сертификат (PDF)'),
        ),
        migrations.AlterField(
            model_name='antiqueitem',
            name='condition',
            field=models.CharField(choices=[('excellent', 'Отличное'), ('good', 'Хорошее'), ('restored', 'С реставрацией')], default='good', max_length=20, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='antiqueitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='antiqueitem',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='antiqueitem',
            name='era',
            field=models.CharField(blank=True, max_length=100, verbose_name='Эпоха'),
        ),
        migrations.AlterField(
            model_name='antiqueitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='antiqueitem',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='antiqueitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='antiqueitem',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='antiqueitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='antiqueitem',
            name='video_review_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видеообзор'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='antique_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.antiqueitem', verbose_name='Антикварный предмет'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='processing', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='antique_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.antiqueitem', verbose_name='Антикварный предмет'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_time',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена на момент заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='AuctionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стартовая цена')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('antique_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_lots', to='core.antiqueitem', verbose_name='Антикварный предмет')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='core.auction', verbose_name='Аукцион')),
            ],
            options={
                'verbose_name': 'Лот аукциона',
                'verbose_name_plural': 'Лоты аукционов',
                'ordering': ['order', 'id'],
            },
        ),
    ]
